### ISSUE TITLE
Block until a new message is received

### ISSUE THREAD

**Issue by antoyo** [Xudong-Huang/may_actor#1]
Hi.
I wonder if there's a way to get a message or block if there's no new message.
For instance, if I want to have a coroutine that process a message queue:
```rust
go!(|| {
    loop {
        let msg = actor.get(); // Block if there's no message.
        // Process msg.
    }
});
```
How can I do that?
Thanks.

**Comment by Xudong-Huang** [comment]
actors receive closures as messages, it will blocked automatically if there is no message to proceed.
But you can call coroutine API that will block the actor to proceed other messages. e.g. if the actor has a `may::sync::mpsc::Receiver` as it's internal state, when you call `recv()` in the message processing, the actor would be blocked until there is some data arrive the channel. 

The most normal cases are calling async IO APIs of `may` in the actor's message processing. the actor would be resumed once the io event is ready.

the best practice is define the actor processing logic in it's method, so every time you want send a message, just call the method within the closure.

each actor internally has a coroutine associated with it. so you don't need to create a coroutine for it.

```rust
struct MyActor {
....
}

impl MyActor {
    fn process_message1(&mut self) {
    ......
    }

    fn process_another_type_message(&mut self) {
     ......
    }
}

// send the message in a loop
let actor = Actor::new(MyActor::new());
loop {
    may::coroutine::sleep(Duration::from_secs(1));
    actor.send(|me| me.process_message1()); 
}

// in another thread/coroutine
let actor_handle = actor.clone();
go!(move ||{
     loop {
         may::coroutine::sleep(Duration::from_secs(1));
         actor_handle.send(|me| me.process_another_type_message());
     }
});


```
